#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf 0
rm -rf AlphaInit
rm -rf constant/*/polyMesh
rm -rf constant/d*
rm -rf system/d*
rm bubbleInfo.csv
#------------------------------------------------------------------------------
